spring:
  profiles:
    active: dev

---
spring:
  application:
    name: springcloud-config-dev
  profiles: dev

---
spring:
  application:
    name: springcloud-config-test
<<<<<<< HEAD:application.yml
  profiles: test
=======
  profiles: test
>>>>>>> 7d48aa109f86c48624d9226e942c266bf737ed31:application.yaml
