spring:
  profiles: 
    active: dev

---
server: 
  port: 9701
#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept

    
#eureka的配置，服务注册到哪里(即注册中心配置的url)
eureka:
  client:
    service-url:
      defaultZone: http://eureka8005.com:8005/eureka/
      
---
#spring配置
server: 
  port: 9702
  
spring:
  profiles: test
  application:
    name: springcloud-provider-dept

    
#eureka的配置，服务注册到哪里(即注册中心配置的url)
eureka:
  client:
    service-url:
      defaultZone: http://eureka8005.com:8005/eureka/